# Generated by Django 3.2.25 on 2025-01-18 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribuyentes',
            fields=[
                ('ruc_cont', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombre_cont', models.CharField(max_length=150)),
                ('direccion_cont', models.CharField(max_length=150)),
                ('referencia_cont', models.CharField(default='N', max_length=150)),
                ('email_cont', models.CharField(max_length=150, null=True)),
                ('razon_social_cont', models.CharField(default='N', max_length=150)),
                ('telefono_cont', models.CharField(max_length=150, null=True)),
                ('celular_cont', models.CharField(max_length=150, null=True)),
                ('activo', models.CharField(default='V', max_length=150)),
                ('representante', models.CharField(max_length=150, null=True)),
                ('parroquia_id', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'contribuyentes',
            },
        ),
        migrations.CreateModel(
            name='Establecimientos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion_est', models.CharField(max_length=150, null=True)),
                ('refeencia_est', models.CharField(default='N', max_length=150, null=True)),
                ('nombre_est', models.CharField(max_length=250, null=True)),
                ('fec_apertura', models.DateField(auto_now_add=True)),
                ('fecha_cierre', models.DateField(auto_now_add=True)),
                ('estado_est', models.CharField(default='V', max_length=1)),
                ('telefono_est', models.CharField(max_length=20, null=True)),
                ('actividad', models.CharField(max_length=250)),
                ('estado', models.CharField(default='ABR', max_length=5)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('contribuyente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribuyenteE', to='contribuyentes.contribuyentes')),
            ],
            options={
                'db_table': 'establecimientos',
            },
        ),
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=250)),
                ('nombre_insp', models.CharField(max_length=250)),
                ('direccion_insp', models.CharField(max_length=250)),
                ('email_insp', models.CharField(max_length=250)),
                ('telefono_insp', models.CharField(max_length=250)),
                ('celular_insp', models.CharField(max_length=250)),
                ('activo', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'inspector',
            },
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'parroquia',
            },
        ),
        migrations.CreateModel(
            name='TiposNegocios',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('anio_desde', models.IntegerField()),
                ('nombre_tip', models.CharField(max_length=250)),
                ('id_categoria', models.CharField(max_length=5)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tipo_lugar', models.CharField(max_length=5)),
                ('anio_hasta', models.IntegerField()),
                ('mes_desde', models.IntegerField()),
                ('mes_hasta', models.IntegerField()),
                ('id_clase', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'tipo_negocio',
            },
        ),
        migrations.CreateModel(
            name='SolicitudInf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now=True)),
                ('numero_soicitud', models.IntegerField(default=None)),
                ('establecimiento', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='establecimientoSo', to='contribuyentes.establecimientos')),
            ],
            options={
                'db_table': 'solicitudinf',
            },
        ),
        migrations.CreateModel(
            name='SolicitudCons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now=True)),
                ('numero_soicitud', models.IntegerField(default=None)),
                ('motivo', models.CharField(default='ABR', max_length=250)),
                ('contribuyente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='solictudesCon', to='contribuyentes.contribuyentes')),
            ],
            options={
                'db_table': 'solicitudcons',
            },
        ),
        migrations.AddField(
            model_name='establecimientos',
            name='parroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parroquiaE', to='contribuyentes.parroquia'),
        ),
        migrations.AddField(
            model_name='establecimientos',
            name='tipo_negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo', to='contribuyentes.tiposnegocios'),
        ),
    ]
