# Generated by Django 3.2.25 on 2025-01-09 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contribuyentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuyentes',
            name='activo',
            field=models.CharField(default='V', max_length=150),
        ),
        migrations.AlterField(
            model_name='contribuyentes',
            name='razon_social_cont',
            field=models.CharField(default='N', max_length=150),
        ),
        migrations.AlterField(
            model_name='establecimientos',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='establecimientos',
            name='estado',
            field=models.CharField(default='ABR', max_length=5),
        ),
        migrations.AlterField(
            model_name='establecimientos',
            name='estado_est',
            field=models.CharField(default='V', max_length=1),
        ),
        migrations.CreateModel(
            name='SolicitudInf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now=True)),
                ('numero_soicitud', models.IntegerField(default=None)),
                ('establecimiento', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='establecimientoSo', to='contribuyentes.establecimientos')),
            ],
            options={
                'db_table': 'solicitudinf',
            },
        ),
        migrations.CreateModel(
            name='SolicitudCons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now=True)),
                ('numero_soicitud', models.IntegerField(default=None)),
                ('motivo', models.CharField(default='ABR', max_length=250)),
                ('contribuyente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='solictudesCon', to='contribuyentes.contribuyentes')),
            ],
            options={
                'db_table': 'solicitudcons',
            },
        ),
    ]
