# Generated by Django 3.2.25 on 2025-01-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribuyentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposnegocios',
            name='codigo',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
    ]
