# Generated by Django 3.2.25 on 2026-03-18 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contribuyentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_informe', models.DateTimeField(auto_now=True)),
                ('numero_informe', models.IntegerField(default=None)),
                ('resultado_informe', models.CharField(default=None, max_length=250)),
                ('observacion', models.CharField(max_length=250, null=True)),
                ('recomendaciones', models.CharField(max_length=250, null=True)),
                ('nrosocilitud', models.IntegerField(default=None)),
                ('tamano', models.CharField(max_length=50, null=True)),
                ('establecimiento', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='establecimientoI', to='contribuyentes.establecimientos')),
            ],
            options={
                'db_table': 'informes',
            },
        ),
        migrations.CreateModel(
            name='InformesConsturccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_informe', models.DateTimeField(auto_now=True)),
                ('numero_informe', models.IntegerField(default=None)),
                ('resultado_informe', models.CharField(default=None, max_length=250)),
                ('observacion', models.CharField(max_length=250, null=True)),
                ('recomendaciones', models.CharField(max_length=250, null=True)),
                ('tipoconstruccion', models.CharField(max_length=250, null=True)),
                ('arealote', models.CharField(max_length=250, null=True)),
                ('tipoesctructura', models.CharField(max_length=250, null=True)),
                ('tamaño', models.CharField(max_length=250, null=True)),
                ('nroplantaconstruidas', models.CharField(max_length=250, null=True)),
                ('nroplantaenconstruccion', models.CharField(max_length=250, null=True)),
                ('areaconstruccion', models.CharField(max_length=250, null=True)),
                ('nrosocilitud', models.IntegerField(default=None)),
                ('establecimiento', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='establecimientoIcon', to='contribuyentes.establecimientos')),
            ],
            options={
                'db_table': 'informescons',
            },
        ),
        migrations.CreateModel(
            name='InformesDetalleCons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
                ('valor', models.BooleanField(default=True)),
                ('categoria', models.CharField(default='varios', max_length=100)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informec', to='informes.informesconsturccion')),
            ],
            options={
                'db_table': 'informe_detalle_cons',
            },
        ),
        migrations.CreateModel(
            name='InformesDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
                ('valor', models.BooleanField(default=True)),
                ('categoria', models.CharField(default='varios', max_length=100)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informed', to='informes.informes')),
            ],
            options={
                'db_table': 'informe_detalle',
            },
        ),
        migrations.CreateModel(
            name='Informeimagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250, null=True)),
                ('imagen', models.ImageField(default=None, upload_to='images/')),
                ('informe', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='informes.informes')),
            ],
            options={
                'db_table': 'informeimagen',
            },
        ),
        migrations.CreateModel(
            name='InformeExtintor',
            fields=[
                ('tipo', models.CharField(max_length=250)),
                ('estado', models.CharField(max_length=250)),
                ('capacidad', models.CharField(max_length=250)),
                ('fecha_caducidad', models.DateField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informee', to='informes.informes')),
            ],
            options={
                'db_table': 'ininforme_det_extintor',
            },
        ),
    ]
