# Generated by Django 3.2.25 on 2024-12-31 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informes',
            name='imagen_informe',
        ),
    ]
