# Generated by Django 3.2.25 on 2025-02-12 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informes',
            name='inspector',
        ),
    ]
