# Generated by Django 3.2.25 on 2025-01-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0002_remove_informes_imagen_informe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informesdetalle',
            name='valor',
            field=models.BooleanField(default=True),
        ),
    ]
