# Generated by Django 3.2.25 on 2025-01-09 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contribuyentes', '0002_auto_20250109_1308'),
        ('informes', '0003_alter_informesdetalle_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformesConsturccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_informe', models.DateTimeField(auto_now=True)),
                ('numero_informe', models.IntegerField(default=None)),
                ('resultado_informe', models.CharField(default=None, max_length=250)),
                ('observacion', models.CharField(max_length=250, null=True)),
                ('recomendaciones', models.CharField(max_length=250, null=True)),
                ('tipoconstruccion', models.CharField(max_length=250, null=True)),
                ('arealote', models.CharField(max_length=250, null=True)),
                ('tipoesctructura', models.CharField(max_length=250, null=True)),
                ('tamaño', models.CharField(max_length=250, null=True)),
                ('nroplantaconstruidas', models.CharField(max_length=250, null=True)),
                ('nroplantaenconstruccion', models.CharField(max_length=250, null=True)),
                ('areaconstruccion', models.CharField(max_length=250, null=True)),
                ('nrosocilitud', models.IntegerField(default=None)),
                ('establecimiento', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='establecimientoIcon', to='contribuyentes.establecimientos')),
            ],
            options={
                'db_table': 'informescons',
            },
        ),
        migrations.RenameField(
            model_name='informesdetalle',
            old_name='id_informe',
            new_name='informe',
        ),
        migrations.AddField(
            model_name='informes',
            name='recomendaciones',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='informes',
            name='tamano',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='informesdetalle',
            name='categoria',
            field=models.CharField(default='varios', max_length=100),
        ),
        migrations.CreateModel(
            name='InformesDetalleCons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
                ('valor', models.BooleanField(default=True)),
                ('categoria', models.CharField(default='varios', max_length=100)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informec', to='informes.informesconsturccion')),
            ],
            options={
                'db_table': 'informe_detalle_cons',
            },
        ),
    ]
