# Generated by Django 3.2.25 on 2025-01-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0004_auto_20250109_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informeextintor',
            old_name='id_informe',
            new_name='informe',
        ),
    ]
