# Generated by Django 3.2.25 on 2026-03-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('i801_codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('i801_nombre', models.CharField(max_length=50)),
                ('i801_clave', models.CharField(max_length=10)),
                ('i801_clase', models.CharField(max_length=3)),
                ('i801_responsable', models.CharField(max_length=3)),
                ('i801_activo', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'i801',
            },
        ),
    ]
